import { useEffect, useState } from "react";
import api from '../services/api.js';
import Papa from "papaparse";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function Reports(){

    const [report, setReport] = useState(null);

    const [from, setFrom] = useState("")
    const [to, setTo] = useState("")

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    useEffect(()=>{

        const getReports = async () => {
            try {
                setLoading(true);
                setError("");

                const response = await api.get(`/reports?from=${from}&to=${to}`)
                setReport(response.data);
            } catch (error) {
                setError(error.response?.data?.message || "Failed to load report");
            } finally {
                setLoading(false);
            }

        }
        getReports();

    }, [from, to])

    const handleClear = () => {
        setFrom("");
        setTo("");
    }

    const handleExport = () => {
        if(!report) return;

        const data = [
            {
                section: "Summary",
                Category: "Total Income",
                Amount: report.totalIncome
            },
            {
                section: "Summary",
                Category: "Total Expense",
                Amount: report.totalExpense
            },
            {
                section: "Summary",
                Category: "Balance",
                Amount: report.balance
            },
            {
                section: "Summary",
                Category: "Top Expense Category",
                Amount: report.topExpenseCategory || "N/A"
            },

            ...report.expenseCategories.map((item)=>({
                Section: "Expense Breakdown",
                Category: item._id,
                Amount: item.total
            }))
        ];

        const csv = Papa.unparse(data);

        const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });

        const url = URL.createObjectURL(blob);

        const link = document.createElement("a");
        link.href = url;
        link.setAttribute("download", `money-metrics-report-${from || "all"}-${to || "all"}.csv`)

        document.body.appendChild(link);

        link.click();

        document.body.removeChild(link);

        URL.revokeObjectURL(url);
    }

    const handleDownloadPDF = () => {
  if (!report) return;

  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.text("Money Metrics", 14, 20);

  doc.setFontSize(14);
  doc.text("Financial Report", 14, 30);

  // Period
  doc.setFontSize(10);

  const period =
    from || to
      ? `Period: ${from || "Beginning"} to ${to || "Present"}`
      : "Period: All Transactions";

  doc.text(period, 14, 40);

  // Summary
  doc.setFontSize(14);
  doc.text("Summary", 14, 55);

  doc.setFontSize(11);

  doc.text(
    `Total Income: Rs. ${report.totalIncome.toLocaleString("en-IN")}`,
    14,
    65
  );

  doc.text(
    `Total Expenses: Rs. ${report.totalExpense.toLocaleString("en-IN")}`,
    14,
    73
  );

  doc.text(
    `Balance: Rs. ${report.balance.toLocaleString("en-IN")}`,
    14,
    81
  );

  doc.text(
    `Top Expense Category: ${report.topExpenseCategory || "N/A"}`,
    14,
    89
  );

  // Expense category table
  const tableData = report.expenseCategories.map((item) => [
    item._id,
    `Rs. ${item.total.toLocaleString("en-IN")}`
  ]);

  autoTable(doc, {
    startY: 105,

    head: [
      ["Expense Category", "Amount"]
    ],

    body: tableData
  });

  // Footer
  const finalY = doc.lastAutoTable?.finalY || 120;

  doc.setFontSize(9);

  doc.text(
    "Generated by Money Metrics",
    14,
    finalY + 15
  );

  // Download
  doc.save(
    `money-metrics-report-${from || "all"}-${to || "all"}.pdf`
  );
};

    if(loading){
        return <p>Loading Report....</p>
    }

    if(error){
        return <p  className="text-red-500">{error}</p>
    }


    return (
        <div>

      {/* Header */}

    <div className="flex items-center justify-between mb-6">

  <div>
    <h2 className="text-2xl font-bold text-gray-800">
      Reports
    </h2>

    <p className="text-gray-500 mt-1">
      Analyze your finances for a selected period.
    </p>
  </div>

 <div className="flex gap-3">

  <button
    onClick={handleExport}
    className="border border-emerald-600 text-emerald-600 px-4 py-2 rounded-lg hover:bg-emerald-50"
  >
    Export CSV
  </button>

  <button
    onClick={handleDownloadPDF}
    className="bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700"
  >
    Download PDF
  </button>

</div>

</div>

      {/* Date Filters */}

      <div className="bg-white border rounded-xl p-4 mb-6">

        <div className="flex flex-col md:flex-row gap-4">

          <div>
            <label className="block text-sm text-gray-600 mb-1">
              From
            </label>

            <input
              type="date"
              value={from}
              onChange={(e) => setFrom(e.target.value)}
              className="border rounded-lg px-4 py-2"
            />
          </div>


          <div>
            <label className="block text-sm text-gray-600 mb-1">
              To
            </label>

            <input
              type="date"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              className="border rounded-lg px-4 py-2"
            />
          </div>


          <div className="flex items-end">
            <button
              onClick={handleClear}
              className="border px-4 py-2 rounded-lg hover:bg-gray-50"
            >
              Clear
            </button>
          </div>

        </div>

      </div>


      {/* Summary Cards */}

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">

        <div className="bg-white border rounded-xl p-5">

          <p className="text-sm text-gray-500">
            Total Income
          </p>

          <h3 className="text-2xl font-bold text-emerald-600 mt-2">
            ₹
            {report?.totalIncome?.toLocaleString(
              "en-IN"
            )}
          </h3>

        </div>


        <div className="bg-white border rounded-xl p-5">

          <p className="text-sm text-gray-500">
            Total Expenses
          </p>

          <h3 className="text-2xl font-bold text-red-500 mt-2">
            ₹
            {report?.totalExpense?.toLocaleString(
              "en-IN"
            )}
          </h3>

        </div>


        <div className="bg-white border rounded-xl p-5">

          <p className="text-sm text-gray-500">
            Balance
          </p>

          <h3 className="text-2xl font-bold text-gray-800 mt-2">
            ₹
            {report?.balance?.toLocaleString(
              "en-IN"
            )}
          </h3>

        </div>


        <div className="bg-white border rounded-xl p-5">

          <p className="text-sm text-gray-500">
            Top Expense Category
          </p>

          <h3 className="text-2xl font-bold text-blue-600 mt-2">
            {report?.topExpenseCategory || "—"}
          </h3>

        </div>

      </div>


      {/* Expense Breakdown */}

      <div className="bg-white border rounded-xl p-5 mt-6">

        <div className="mb-5">

          <h3 className="text-lg font-semibold text-gray-800">
            Expenses by Category
          </h3>

          <p className="text-sm text-gray-500">
            Spending breakdown for the selected period.
          </p>

        </div>


        {report?.expenseCategories?.length === 0 ? (

          <div className="py-8 text-center">

            <p className="text-gray-500">
              No expense data found for this period.
            </p>

          </div>

        ) : (

          <div className="overflow-x-auto">

            <table className="w-full text-sm">

              <thead>

                <tr className="border-b bg-gray-50 text-left text-gray-500">

                  <th className="px-5 py-4">
                    Category
                  </th>

                  <th className="px-5 py-4 text-right">
                    Amount
                  </th>

                </tr>

              </thead>

              <tbody>

                {report?.expenseCategories?.map(
                  (category) => (

                    <tr
                      key={category._id}
                      className="border-b last:border-b-0"
                    >

                      <td className="px-5 py-4">
                        {category._id}
                      </td>

                      <td className="px-5 py-4 text-right font-semibold text-red-500">
                        ₹
                        {category.total.toLocaleString(
                          "en-IN"
                        )}
                      </td>

                    </tr>

                  )
                )}

              </tbody>

            </table>

          </div>

        )}

      </div>

    </div>
  )
}

export default Reports;