import { useEffect, useState } from "react";
import api from "../services/api.js";
import Papa from "papaparse";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import {
  CalendarDays,
  Download,
  FileSpreadsheet,
  TrendingUp,
  TrendingDown,
  Wallet,
  Trophy
} from "lucide-react";

function Reports() {
  const [report, setReport] = useState(null);

  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const getReports = async () => {
      try {
        setLoading(true);
        setError("");

        const response = await api.get(
          `/reports?from=${from}&to=${to}`
        );

        setReport(response.data);

      } catch (error) {
        setError(
          error.response?.data?.message ||
          "Failed to load report"
        );

      } finally {
        setLoading(false);
      }
    };

    getReports();

  }, [from, to]);


  const handleClear = () => {
    setFrom("");
    setTo("");
  };


  const handleExport = () => {
    if (!report) return;

    const data = [
      {
        Section: "Summary",
        Category: "Total Income",
        Amount: report.totalIncome
      },
      {
        Section: "Summary",
        Category: "Total Expense",
        Amount: report.totalExpense
      },
      {
        Section: "Summary",
        Category: "Balance",
        Amount: report.balance
      },
      {
        Section: "Summary",
        Category: "Top Expense Category",
        Amount: report.topExpenseCategory || "N/A"
      },

      ...report.expenseCategories.map((item) => ({
        Section: "Expense Breakdown",
        Category: item._id,
        Amount: item.total
      }))
    ];

    const csv = Papa.unparse(data);

    const blob = new Blob(
      [csv],
      {
        type: "text/csv;charset=utf-8;"
      }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.setAttribute(
      "download",
      `money-metrics-report-${from || "all"}-${to || "all"}.csv`
    );

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };


  const handleDownloadPDF = () => {
    if (!report) return;

    const doc = new jsPDF();

    // Title

    doc.setFontSize(20);

    doc.text(
      "Money Metrics",
      14,
      20
    );

    doc.setFontSize(14);

    doc.text(
      "Financial Report",
      14,
      30
    );


    // Period

    doc.setFontSize(10);

    const period =
      from || to
        ? `Period: ${from || "Beginning"} to ${to || "Present"}`
        : "Period: All Transactions";

    doc.text(
      period,
      14,
      40
    );


    // Summary

    doc.setFontSize(14);

    doc.text(
      "Summary",
      14,
      55
    );

    doc.setFontSize(11);

    doc.text(
      `Total Income: Rs. ${report.totalIncome.toLocaleString(
        "en-IN"
      )}`,
      14,
      65
    );

    doc.text(
      `Total Expenses: Rs. ${report.totalExpense.toLocaleString(
        "en-IN"
      )}`,
      14,
      73
    );

    doc.text(
      `Balance: Rs. ${report.balance.toLocaleString(
        "en-IN"
      )}`,
      14,
      81
    );

    doc.text(
      `Top Expense Category: ${
        report.topExpenseCategory || "N/A"
      }`,
      14,
      89
    );


    // Expense category table

    const tableData =
      report.expenseCategories.map(
        (item) => [
          item._id,

          `Rs. ${item.total.toLocaleString(
            "en-IN"
          )}`
        ]
      );

    autoTable(doc, {
      startY: 105,

      head: [
        [
          "Expense Category",
          "Amount"
        ]
      ],

      body: tableData
    });


    // Footer

    const finalY =
      doc.lastAutoTable?.finalY || 120;

    doc.setFontSize(9);

    doc.text(
      "Generated by Money Metrics",
      14,
      finalY + 15
    );


    // Download

    doc.save(
      `money-metrics-report-${from || "all"}-${to || "all"}.pdf`
    );
  };


  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[300px]">

        <p className="text-gray-500">
          Loading report...
        </p>

      </div>
    );
  }


  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-xl p-4">

        <p className="text-red-600">
          {error}
        </p>

      </div>
    );
  }


  return (
    <div className="w-full">

      {/* Header */}

      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-6">

        <div>

          <h2 className="text-xl sm:text-2xl font-bold text-gray-800">
            Reports
          </h2>

          <p className="text-sm sm:text-base text-gray-500 mt-1">
            Analyze your finances for a selected period.
          </p>

        </div>


        {/* Export Buttons */}

        <div className="flex flex-col sm:flex-row gap-3">

          <button
            onClick={handleExport}
            disabled={!report}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 border border-emerald-300 text-emerald-700 px-4 py-2.5 rounded-lg hover:bg-emerald-50 disabled:opacity-50 transition"
          >
            <FileSpreadsheet size={18} />

            Export CSV
          </button>


          <button
            onClick={handleDownloadPDF}
            disabled={!report}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-emerald-600 text-white px-4 py-2.5 rounded-lg hover:bg-emerald-700 disabled:opacity-50 transition"
          >
            <Download size={18} />

            Download PDF
          </button>

        </div>

      </div>


      {/* Date Filters */}

      <div className="bg-white border border-gray-200 rounded-xl p-4 sm:p-5 mb-6">

        <div className="flex items-center gap-2 mb-4">

          <CalendarDays
            size={19}
            className="text-emerald-600"
          />

          <h3 className="font-semibold text-gray-800">
            Report Period
          </h3>

        </div>


        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto] gap-4">

          {/* From */}

          <div>

            <label className="block text-sm text-gray-600 mb-1.5">
              From
            </label>

            <input
              type="date"
              value={from}
              onChange={(e) =>
                setFrom(e.target.value)
              }
              className="w-full h-11 border border-gray-300 rounded-lg px-4 outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
            />

          </div>


          {/* To */}

          <div>

            <label className="block text-sm text-gray-600 mb-1.5">
              To
            </label>

            <input
              type="date"
              value={to}
              onChange={(e) =>
                setTo(e.target.value)
              }
              className="w-full h-11 border border-gray-300 rounded-lg px-4 outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
            />

          </div>


          {/* Clear */}

          <div className="flex items-end">

            <button
              onClick={handleClear}
              className="w-full lg:w-auto h-11 border border-gray-300 text-gray-700 px-5 rounded-lg hover:bg-gray-50 transition"
            >
              Clear
            </button>

          </div>

        </div>

      </div>


      {/* Summary Cards */}

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">

        {/* Income */}

        <div className="bg-white border border-gray-200 rounded-xl p-5 flex items-center gap-4">

          <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center shrink-0">

            <TrendingUp
              size={23}
              className="text-emerald-600"
            />

          </div>


          <div className="min-w-0">

            <p className="text-sm text-gray-500">
              Total Income
            </p>

            <h3 className="text-xl sm:text-2xl font-bold text-emerald-600 mt-1 break-words">
              ₹
              {report?.totalIncome?.toLocaleString(
                "en-IN"
              )}
            </h3>

          </div>

        </div>


        {/* Expenses */}

        <div className="bg-white border border-gray-200 rounded-xl p-5 flex items-center gap-4">

          <div className="w-12 h-12 rounded-xl bg-red-100 flex items-center justify-center shrink-0">

            <TrendingDown
              size={23}
              className="text-red-500"
            />

          </div>


          <div className="min-w-0">

            <p className="text-sm text-gray-500">
              Total Expenses
            </p>

            <h3 className="text-xl sm:text-2xl font-bold text-red-500 mt-1 break-words">
              ₹
              {report?.totalExpense?.toLocaleString(
                "en-IN"
              )}
            </h3>

          </div>

        </div>


        {/* Balance */}

        <div className="bg-white border border-gray-200 rounded-xl p-5 flex items-center gap-4">

          <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center shrink-0">

            <Wallet
              size={23}
              className="text-blue-600"
            />

          </div>


          <div className="min-w-0">

            <p className="text-sm text-gray-500">
              Balance
            </p>

            <h3 className="text-xl sm:text-2xl font-bold text-gray-800 mt-1 break-words">
              ₹
              {report?.balance?.toLocaleString(
                "en-IN"
              )}
            </h3>

          </div>

        </div>


        {/* Top Category */}

        <div className="bg-white border border-gray-200 rounded-xl p-5 flex items-center gap-4">

          <div className="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center shrink-0">

            <Trophy
              size={23}
              className="text-purple-600"
            />

          </div>


          <div className="min-w-0">

            <p className="text-sm text-gray-500">
              Top Expense Category
            </p>

            <h3 className="text-xl sm:text-2xl font-bold text-purple-600 mt-1 truncate">
              {report?.topExpenseCategory || "—"}
            </h3>

          </div>

        </div>

      </div>


      {/* Expense Breakdown */}

      <div className="bg-white border border-gray-200 rounded-xl p-4 sm:p-5 mt-6">

        <div className="mb-5">

          <h3 className="text-base sm:text-lg font-semibold text-gray-800">
            Expenses by Category
          </h3>

          <p className="text-sm text-gray-500 mt-1">
            Spending breakdown for the selected period.
          </p>

        </div>


        {report?.expenseCategories?.length === 0 ? (

          <div className="py-10 text-center">

            <p className="text-gray-500 text-sm">
              No expense data found for this period.
            </p>

          </div>

        ) : (

          <div className="overflow-x-auto">

            <table className="w-full min-w-[450px] text-sm">

              <thead>

                <tr className="border-b border-gray-200 bg-gray-50/70 text-left text-gray-500">

                  <th className="px-4 sm:px-5 py-4 font-medium">
                    Category
                  </th>

                  <th className="px-4 sm:px-5 py-4 text-right font-medium">
                    Amount
                  </th>

                </tr>

              </thead>


              <tbody>

                {report?.expenseCategories?.map(
                  (category) => (

                    <tr
                      key={category._id}
                      className="border-b border-gray-100 last:border-b-0 hover:bg-gray-50/70 transition"
                    >

                      <td className="px-4 sm:px-5 py-4 font-medium text-gray-800">
                        {category._id}
                      </td>

                      <td className="px-4 sm:px-5 py-4 text-right font-semibold text-red-500 whitespace-nowrap">
                        ₹
                        {category.total.toLocaleString(
                          "en-IN"
                        )}
                      </td>

                    </tr>

                  )
                )}

              </tbody>

            </table>

          </div>

        )}

      </div>

    </div>
  );
}

export default Reports;